export enum ActivityType {
  UPLOADED = 'UPLOADED',
  VIEWED = 'VIEWED',
  UPDATED = 'UPDATED',
  SHARED = 'SHARED',
  DOWNLOADED = 'DOWNLOADED',
  RESTORED = 'RESTORED',
  MOVED = 'MOVED',
  FAVORITED = 'FAVORITED',
  UNFAVORITED = 'UNFAVORITED',
  DELETED='DELETED',
  CREATED='CREATED'
}
